### PR TITLE
Install Paris Traceroute

### PR DESCRIPTION
**Pull request by toreanderson**
Paris Traceroute is an ECMP-aware traceroute implementation. It can discover
and report on all unique ECMP / load balanced paths betweeen itself and the
destination, which can be very useful for debugging purposes.

Homepage: https://paris-traceroute.net

### CODE REVIEW

**Comment by sndrsmnk** [comment]
Looks sane. Nifty tool. Thanks!

**Comment by sndrsmnk** [comment]
Hm. Needs root though.

**Comment by toreanderson** [comment]
> Hm. Needs root though.

You sure? When I tested, it worked fine with only the `cap_net_raw,cap_net_admin=eip` capabilities my patch adds.

**Comment by sndrsmnk** [comment]
I didn't notice the setcap task, thought it was just an 'add this package'-merge.
Great. Thanks!

**Pull request merged**
