### PR TITLE
Add QuxLabs RTs

### PR DESCRIPTION
**Pull request by f0o**
Sessions are configured on our side :)

### CODE REVIEW

**Comment by f0o** [comment]
Good point, will remove RT2

**Comment by f0o** [comment]
HI @arjenz,

I was wondering when this config will be applied. Our sessions is still in `connecting` and am wondering if this is an issue on our end or not 🤔 

Cheers
/f0o

**Comment by arjenz** [comment]
@f0o Good catch, normally it takes about an hour or two, but as your peer IP ends in `::` it actually needed quoting, so our automation choked on it due to yaml being yaml. I pushed a fix, it should be live shortly.

**Comment by arjenz** [comment]
@f0o I triggered automation manually, IPv6 is happy, v4 not yet:

```
QUXLABS1-v4            203038          0          0     0 00:01:36 Connect
QUXLABS1-v6            203038      50886          6     0 00:01:31  19355
```

```
# telnet 185.243.23.254 179
Trying 185.243.23.254...
```

getting timeout

**Comment by f0o** [comment]
Sneaky YAML!

The timeout might be expected as we filter incomming tcp/179 unless from linknets. I've opened it up for 212.114.120.72/32.

What's odd is that our side should've been connecting to your side tho 🤔 

I'll keep an eye on the session though the day, hopefully the FW change did the trick if not I might need to double check the BGP setup on our end.

**Pull request merged**
