### PR TITLE
Update peers.yml

### PR DESCRIPTION
**Pull request by securebitag**
Add additional locations for AS58057

### CODE REVIEW

**Comment by teunvink** [comment]
Can you please explain in what way all these sessions differ? What are the benefits of adding so many sessions to the looking glass from one ASN? We prefer to keep the number of (mostly) identical sessions limited to spare resources on our LG.

**Comment by securebitag** [comment]
Locations have different clients, routes and internet exchange connections. As most of the locations are not connected together, they have different routes.
You can verify at www.asns.info if needed.

**Comment by teunvink** [comment]
I understand. However, since resources are not unlimited and we like to offer a diverse set of ASNs, I would appreciate it if you could reduce the list of sessions to your ASN to 2 or 3.

**Comment by securebitag** [comment]
Hi

Understand. I have changed to 3 sessions in total.
Thank you.

**Comment by teunvink** [comment]
Excellent. Sessions have been configured on our side but seem to be down now:
```
root@lg02:~# bgpctl show | grep SECUR
SECUREBIT_ZUR01-v4      58057          0          2     0 Never    Connect
SECUREBIT_ZUR01-v6      58057          0          9     0 Never    Connect
SECUREBIT_ZUR02-v4      58057          0          2     0 Never    Connect
SECUREBIT_ZUR02-v6      58057          0          6     0 Never    Connect
SECUREBIT_FRE01-v4      58057          0          0     0 Never    Connect
SECUREBIT_FRE01-v6      58057          0          3     0 Never    Active
```

I assume your side hasn't been configured yet?

**Pull request merged**
