### PR TITLE
Add ROOTNL to peers.yml

### PR DESCRIPTION
**Pull request by TomBuyvoets**

### CODE REVIEW

**Comment by teunvink** [comment]
Our side is configured, but sessions are still down. Looks like ROOTNL's side hasn't been configured or TCP/179 is blocked:
```
Oct 24 13:22:30 lg02 bgpd[101680]: neighbor 217.119.226.1 (ROOTNL1-v4): socket error: Connection refused
Oct 24 13:22:30 lg02 bgpd[101680]: neighbor 217.119.226.1 (ROOTNL1-v4): state change Connect -> Active, reason: Connection open failed
Oct 24 13:22:30 lg02 bgpd[101680]: neighbor 2a02:1398:800:5000::1:1 (ROOTNL1-v6): socket error: Connection refused
Oct 24 13:22:30 lg02 bgpd[101680]: neighbor 2a02:1398:800:5000::1:1 (ROOTNL1-v6): state change Connect -> Active, reason: Connection open failed
```

**Comment by TomBuyvoets** [comment]
Root will configure there side on friday 28-10.

**Comment by TomBuyvoets** [comment]
We see `bad peer AS number`. We have set AS199036 at our side. Our as number is 16350. Did you set the right AS number at your side?

```
IP Address: 212.114.120.72, AS: 199036 (EBGP), RouterID: 0.0.0.0, VRF: default-vrf
       Description: NLNOG_LG
    State: ACTIVE, Time: 0h40m45s, KeepAliveTime: 30, HoldTime: 90
    Minimal Route Advertisement Interval: 0 seconds
       Multihop-EBGP: yes, ttl: 10
       UpdateSource: Address 217.119.226.1
       RefreshCapability: Received
       GracefulRestartCapability: Sent
           Restart Time 120 sec, Restart bit 0
           afi/safi 1/1, Forwarding bit 0
    Address Family : IPV4 Unicast
       Prefix-list: (in) deny_all_in
    Messages:    Open    Update  KeepAlive Notification Refresh-Req
       Sent    : 2       0       0         0            0
       Received: 0       0       0         0            0
    Last Connection Reset Reason:Bad Peer AS Number
    Notification Sent:     Open Message Error/Bad Peer AS Number
    Notification Received: Hold Timer Expired
    Neighbor NLRI Negotiation:
      Peer configured for IPV4 unicast  Routes
    Neighbor ipv6 MPLS Label Capability Negotiation:
    Neighbor AS4 Capability Negotiation:
    Outbound Policy Group:
       ID: 6, Use Count: 6
       Last update time was 3 sec ago
    BFD:Disabled

```

**Comment by arjenz** [comment]
`Neighbor AS4 Capability Negotiation:` shows empty in your output, did you enable 32 bits ASNs on your end?

**Comment by teunvink** [comment]
In addition: TCP/179 seems to be unreachable for IPv6:

```
root@lg02:~# telnet 2a02:1398:800:5000::1:1 179
Trying 2a02:1398:800:5000::1:1...
telnet: Unable to connect to remote host: Connection refused
```

The IPv4 session seems to be up now:
```
root@lg02:~# bgpctl show neighbor ROOTNL1-v4
BGP neighbor is 217.119.226.1, remote AS 16350, Multihop (255)
 Description: ROOTNL1-v4
  BGP version 4, remote router-id 217.119.226.1
  BGP state = Established, up for 00:05:38
  Last read 00:00:00, holdtime 90s, keepalive interval 30s
  Last write 00:00:08
  Neighbor capabilities:
    Multiprotocol extensions: IPv4 unicast
    4-byte AS numbers
    Route Refresh
    Graceful Restart: Timeout: 120, IPv4 unicast
  Negotiated capabilities:
    Multiprotocol extensions: IPv4 unicast
    4-byte AS numbers
    Route Refresh
    Graceful Restart: Timeout: 120, IPv4 unicast

  Message statistics:
                  Sent       Received
  Opens                   41         40
  Notifications            0         38
  Updates                  2     388746
  Keepalives             713          2
  Route Refresh            0          0
  Total                  756     388826

  Update statistics:
                  Sent       Received   Pending
  Prefixes                 0     897203
  Updates                  0    1939830          0
  Withdraws                0      12289          0
  End-of-Rib               2          2
  Route Refresh statistics:
  Request                  0          0
  Begin-of-RR              0          0
  End-of-RR                0          0

  Local host:        212.114.120.72, Local port:    179
  Remote host:        217.119.226.1, Remote port:  8196
```

**Pull request merged**
